version: '0.1'
services:
  crawler_twse:
    image: crawler:0.0.1
    hostname: "twse"
    command: pipenv run celery -A financialdata.tasks.worker worker --loglevel=info --concurrency=1 --hostname=%h -Q twse
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network
    
networks:
  my_network:
    external: true
